Task 6 completed (Burachenko)
elefus/epam-leti-10-2017 pull request #102
Opened 2017-11-04 20:37 UTC by AlexMem

2017-11-15 20:08 UTC, Hitsugaya7 commented on src/main/java/com/epam/jf/burachenko/homework/Task6.java
> +    private static boolean isFirstInAlphabet(String s1, String s2) {
Неправильно сортирует в лексикографическом порядке
Задаю такие входные параметры : a A Z asdv we ew rez ret
Получаю такие выходные параметры a Z A we ew rez ret asdv

2017-11-16 02:23 UTC, NikitaShabashov commented
Уже есть реализованные методы сортировки. Я думаю это задание предполагало использование компаратора и встроенных методов сортировки массивов.

2017-11-16 20:13 UTC, tehwalkingwind approved these changes

2017-11-17 06:22 UTC, iBavtovich requested changes

2017-11-17 06:22 UTC, iBavtovich commented on src/main/java/com/epam/jf/burachenko/homework/Task6.java
> +            if(s1.charAt(i) != s2.charAt(i)) {
Вот здесь надо учесть что маленькая и заглавная буквы равны, иначе сортировать строки будет не совсем правильно. Например: Bcda и badc

2017-11-22 10:50 UTC, RicoRodriges commented on src/main/java/com/epam/jf/burachenko/homework/Task6.java
> +            if(s1.charAt(i) != s2.charAt(i)) {
А ещё лучше использовать метод compareTo у класса String

2018-01-10 23:26 UTC, Andrewisnew approved these changes

2026-08-19 13:37 UTC, closed without merging