Task7 completed (Guba)
elefus/epam-leti-10-2017 pull request #103
Opened 2017-11-04 21:08 UTC by Criptonite

Create own AbstractIntList implementation. Create own exception for indexOf and lastIndexOf methods. Create test class with entry point.

2017-11-16 20:01 UTC, RicoRodriges reviewed
Зачем поле capacity, если есть values.length?
Ошибка: Task7 task7 = new Task7(0); task7.add(1);

2017-11-17 07:08 UTC, iBavtovich commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        this.size = 0;
Вот тут наверное size надо не 0 равным делать?

2017-11-19 21:44 UTC, IlyasYOY approved these changes

2017-12-15 13:34 UTC, elefus requested changes
Посмотри замечания и прогони тест, предложенный @RicoRodriges - он действительно падает.

2017-12-15 13:34 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/NoSuchElementException.java
> +public class NoSuchElementException extends RuntimeException {
А чем не удовлетворил стандартный `java.util.NoSuchElementException`?)

2017-12-15 13:34 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        super();
Явный вызов родительского конструктора без параметров избыточен.

2017-12-15 13:34 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        this.size = 0;
Зачем использовать `this`, если перекрытия имен в данной области видимости нет?
Какое значение по умолчанию имеет поле `size`?

2017-12-15 13:34 UTC, elefus commented on src/main/java/com/epam/jf/common/homework/task7/AbstractIntArrayList.java
> +    this.values = new int[10];
MagicNumber - лучше вынести в виде private-константы класса `DEFAULT_SIZE`

2017-12-15 13:34 UTC, elefus commented on src/main/java/com/epam/jf/common/homework/task7/AbstractIntArrayList.java
> +    this.values = new int[(int) (list.values.length * 1.5)];
Зачем использовать `this`, если перекрытия имен в данной области видимости нет?
Почему размер создаваемого листа в 1.5 раза больше исходного?
Если исходный список содержит `Integer.MAX_VALUE - 1` элементов, к чему приведет его копирование?

2017-12-15 13:34 UTC, elefus commented on src/main/java/com/epam/jf/common/homework/task7/AbstractIntArrayList.java
> +      this.values[i] = list.values[i];
Перебор элементов и их запись - не очень эффективный способ копирования массива, существует более оптимальный.

2017-12-15 13:34 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +    protected int capacity;
Какой смысл от этого поля, если ты в любой момент можешь обратиться к `values.length`?

2017-12-15 13:34 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        return newSize > capacity * 0.75;
Всегда будут незадействованные 25% в массиве?

2017-12-15 13:34 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +    public int getCapacity() {
Зачем "светить" наружу своим внутренним состоянием?

2017-12-15 13:34 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        for (int i = 0; i < size; i++) {
Перебор элементов и их запись - не очень эффективный способ копирования массива, существует более оптимальный.

2017-12-20 13:19 UTC, elefus requested changes
Посмотри комментарии

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/common/homework/task7/AbstractIntArrayList.java
> +        values = new int[(int) (list.values.length)];
Посмотри на метод `Arrays.copyOf`

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/common/homework/task7/AbstractIntArrayList.java
> +        values = new int[(int) (list.values.length)];
Зачем явный каст к `int`?

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/common/homework/task7/AbstractIntArrayList.java
> +        this.values = new int[DEFAULT_SIZE];
Зачем использовать явную ссылку `this`, если перекрытия имен в данной области видимости не наблюдается?

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        int olldSize = size;
Опечатка: `oldSize`

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        return size > olldSize;
Аналогичный код расположен в методе `add(value, index)` - достаточно возвращать результат выполнения этого метода.

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        if (index > size || index < 0) {
Обычно сначала проверяют левую границу, потом правую.

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +            if (isNeedExpand(size + 1)) {
Везде где вызывается этот метод он участвует в блоке `if`, после чего осуществляется вызов метода `expand`. Возможно стоит объединить их, назвав `expandIfNeeded`

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +    private void expand() {
Посмотри на метод `Arrays.copyOf` - с помощью него можно сильно сократить тело данного метода

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +    private void shifftRight(int fromInclusive, int positions) {
Опечатка: `shifFtRight`
Этот метод всегда вызывается со вторым аргументом равным `1`, имеет ли смысл его передавать?

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        for (int i = fromInclusive; i < (fromInclusive + positions); i++) {
Зачем занулять элементы?
Они все равно будут перезаписаны дальше.

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        while (isNeedExpand(size + positions)) {
Проверку можно вынести из этого метода в `add` - позволит сократить дублирование.

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        size += positions;
Инкремент можно вынести из этого метода в `add` - позволит сократить дублирование.

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        if (fromInclusive - position < 0) {
Этот блок кода встречается во многих местах, возможно стоит его вынести в отдельный метод `rangeCheck(int) throws IndexOutOfBoundsException`?

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +            values[index] = 0;
Необходимо ли занулять удаляемый элемент?
Ведь получить значение все равно нет возможностей.

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +    private void shiftLeft(int fromInclusive, int position) {
Этот метод всегда вызывается со вторым аргументом равным 1, имеет ли смысл его передавать?

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        size -= position;
Декремент можно вынести из этого метода в `remove` - позволит сократить дублирование.

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +    public boolean addAll(AbstractIntArrayList list) {
Определенно не самая эффективная реализация (вставка в конец массива по одному элементу).
Можно было бы воспользоваться копированием части массива.

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        for (int element : values) {
1) Этим действием ты не зануляешь значение в массиве, а переписываешь локальную переменную `element`.
2) Есть ли в принципе необходимость занулять элементы в массиве?

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        return this.size;
Зачем использовать явную ссылку `this`, если перекрытия имен в данной области видимости не наблюдается?

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +    public AbstractIntArrayList subList(int fromInclusive, int toInclusive) {
Идея саб-листа в неразрывной связи с исходным, но в рамках этого задания можешь оставить как есть)

2017-12-20 13:19 UTC, elefus commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        Task7 newList = new Task7();
Есть же конструктор, принимающий `AbstractIntArrayList`.

2018-01-02 21:09 UTC, Criptonite commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +        Task7 newList = new Task7();
Он вроде тут не поможет.

2018-01-02 21:09 UTC, Criptonite commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +    public AbstractIntArrayList subList(int fromInclusive, int toInclusive) {
Оставил как было.

2018-01-02 21:28 UTC, Criptonite commented on src/main/java/com/epam/jf/guba/homework/task7/Task7.java
> +    public boolean addAll(AbstractIntArrayList list) {
Исправил

2022-04-20 19:54 UTC, closed without merging