Task7 completed (Kruglik)
elefus/epam-leti-10-2017 pull request #104
Opened 2017-11-05 13:27 UTC by kruglikalexey

Task7 completed

2017-11-16 20:13 UTC, RicoRodriges requested changes
Если создать объект на основе другого списка, то в нём будет на 1 элемент меньше

2017-11-23 21:58 UTC, iBavtovich commented on src/main/java/com/epam/jf/kruglik/homework/task7/IntArrayList.java
> +        if (size>0){
описочка вышла :)

2017-11-23 21:59 UTC, iBavtovich approved these changes

2017-11-23 22:00 UTC, iBavtovich commented on src/main/java/com/epam/jf/kruglik/homework/task7/IntArrayList.java
> +        this.capacity = list.size() - 1;
единички ни к чему

2017-12-20 22:09 UTC, Demetresko approved these changes

2018-01-10 23:45 UTC, Andrewisnew approved these changes

2026-08-19 13:37 UTC, closed without merging