Task9 completed (Kruglik)
elefus/epam-leti-10-2017 pull request #160
Opened 2017-11-13 17:13 UTC by kruglikalexey

task9 and unit test completed

2017-11-16 04:01 UTC, shabashoff approved these changes

2017-11-17 09:16 UTC, egakupi requested changes

2017-11-17 09:16 UTC, egakupi commented on test/com/epam/jf/kruglik/homework/Task9Test.java
> +        Assertions.assertTrue(Task9.isPowerOfTwo(0));
0 же не является степенью двойки

2017-11-17 14:14 UTC, gudmian requested changes
Ошибка при нуле. Правильно еще проверить на 0 вот так:  n != 0 && (твое условие)

2018-01-02 19:35 UTC, kruglikalexey commented on test/com/epam/jf/kruglik/homework/Task9Test.java
> +        Assertions.assertTrue(Task9.isPowerOfTwo(0));
Косячок=)

2018-01-11 00:11 UTC, Andrewisnew approved these changes

2018-01-13 15:10 UTC, AlexMem approved these changes

2026-08-19 13:37 UTC, closed without merging