Task14 completed (Kruglik)
elefus/epam-leti-10-2017 pull request #164
Opened 2017-11-13 21:53 UTC by kruglikalexey

task14 and unit tests added.

2017-11-17 14:26 UTC, gudmian requested changes
В условии написанно, что нужно возвращать новую матрицу, а ты просто сортируешь переданную тебе. Я сам сначала сортировал входную матрицу, а потом посмотрел еще раз на условие и переделал (не знаю зря или не зря, пусть Коля решит). Еще можно проверить входные параметры и кинуть исключение если вдруг с ними будет что-то не так.

2017-12-10 09:39 UTC, iBavtovich approved these changes

2017-12-20 22:11 UTC, Demetresko approved these changes

2018-01-11 00:29 UTC, Andrewisnew approved these changes

2018-01-13 15:34 UTC, Awethon approved these changes

2026-08-19 13:37 UTC, closed without merging