Task7 completed
elefus/epam-leti-10-2017 pull request #166
Opened 2017-11-14 17:58 UTC by Hitsugaya7

2017-12-10 09:27 UTC, iBavtovich requested changes

2017-12-10 09:27 UTC, iBavtovich commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        for (int i = 0; i < index-1; i++) {
Для копирования массива есть System.arraycopy

2017-12-10 09:27 UTC, iBavtovich commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        return values[index-1];
не index-1, а index

2017-12-10 09:27 UTC, iBavtovich commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        if(this.size()!=list.size())
Эти списки могут быть разной длины, но один из них не может быть меньше другого.

2017-12-10 09:27 UTC, iBavtovich commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        for (int i = 0; i < index - 1; i++) {
опять с индексами что-то. может я не понял чего-то, но если я хочу удалить 0-ой, то он попытается мне вернуть -1 ?

2017-12-10 09:27 UTC, iBavtovich commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        return -11;
Чего -11? :)

2017-12-10 09:27 UTC, iBavtovich commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        for (int i = 0; i <values.length ; i++) {
Можно просто с конца перебирать элементы

2018-01-11 15:01 UTC, Hitsugaya7 commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        for (int i = 0; i < index-1; i++) {
я не считаю это ошибкой

2018-01-11 15:02 UTC, Hitsugaya7 commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        return values[index-1];
ну я писал для пользователя, который не знает что в массиве индексы начинаются с 9

2018-01-11 15:03 UTC, Hitsugaya7 commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        if(this.size()!=list.size())
чего?

2018-01-11 15:03 UTC, Hitsugaya7 commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        for (int i = 0; i < index - 1; i++) {
ну я писал для пользователя, который не знает что в массиве индексы начинаются с 0

2018-01-11 15:03 UTC, Hitsugaya7 commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        return -11;
ну да)

2018-01-11 15:04 UTC, Hitsugaya7 commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        for (int i = 0; i <values.length ; i++) {
ну это тоже не ошибка)

2018-01-11 15:51 UTC, iBavtovich commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        if(this.size()!=list.size())
Ну есть список (этот) его размер 10: 0, 1, ..., 9, а есть второй (лист) в нем 2 элемента: 1, 2. Ты делаешь проверку, их размеры не совпадают и возвращаешь false.

2018-01-11 15:52 UTC, iBavtovich commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        for (int i = 0; i < index - 1; i++) {
сорри понял, ну я тоже остальное не считал ошибку, просто так написал. Ну а логика conyainsAll вроде бы неправильная

2018-01-11 16:43 UTC, MrBender13 commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        if(this.size()!=list.size())
Можно вопрос, какая зависимость между размерами?

2018-01-11 16:48 UTC, MrBender13 commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        if(this.size()!=list.size())
Если this больше list: this размера 10 (0, 1, 2..... 9) list размера 2 (0, 1); Если this меньше лист: this размера 2(0,1) list размера 10 (1,1,1...1). Разве размеры не могут быть любыми?

2018-01-11 19:45 UTC, iBavtovich commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        if(this.size()!=list.size())
Ну я примерно этотимел ввиду, просто не знал чего там завязано на размере что-то

2018-01-11 20:59 UTC, Hitsugaya7 commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        for (int i = 0; i < index - 1; i++) {
согласен, исправлю) спасибо)

2018-01-11 21:39 UTC, Hitsugaya7 commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        if(this.size()!=list.size())
исправил

2018-01-12 18:31 UTC, Andrewisnew commented on src/main/java/com/epam/jf/ilyassov/homework/IntArrayList.java
> +        return values[index-1];
не, ну ты ж не забывай, что у массивов по определению индексация с 0 + твоим классом будут пользоваться люди, которые прогают, и это их чутка запутает)

2018-01-13 15:40 UTC, AlexMem commented on src/main/java/com/epam/jf/ilyassov/homework/AbstractIntArrayList.java
>      public AbstractIntArrayList(AbstractIntArrayList list) {
length забыл поменять) И разве не надо именно копировать list.values в values, а не передавать values ссылку на list.values? В нынешней ситуации, если что-нибудь поменять в values - это отразится на list.values, потому что они ссылаются на один массив

2026-04-23 16:59 UTC, closed without merging