Task8 completed
elefus/epam-leti-10-2017 pull request #167
Opened 2017-11-14 18:01 UTC by Hitsugaya7

2017-11-16 17:11 UTC, tehwalkingwind requested changes

2017-11-16 17:11 UTC, tehwalkingwind commented on src/main/java/com/epam/jf/ilyassov/homework/Task8.java
> +            }
А если во входных данных будут не только числа?

2017-11-16 17:11 UTC, tehwalkingwind commented on src/main/java/com/epam/jf/ilyassov/homework/Task8.java
> +                return false;
Код не проверяет центральные символы в передаваемой строке.

2017-11-17 13:40 UTC, RicoRodriges requested changes
После нахождения второго слова можно остановиться.
После 10 раз проверки по регулярному выражению на 11 раз, можешь мне проверить, результат не изменится.

2017-11-20 11:56 UTC, RicoRodriges commented
На регулярное выражение зачем несколько раз проверять?

2017-12-10 09:11 UTC, iBavtovich approved these changes

2017-12-10 09:11 UTC, iBavtovich commented on src/main/java/com/epam/jf/ilyassov/homework/Task8.java
> +            if(!arr.matches("\\d+")) {
Это сразу проверка всей строки (строка в которой будет 1 или более цифр), так что цикл не нужен.

2018-01-11 01:05 UTC, Andrewisnew approved these changes
Согласен с iBavtovich

2018-01-13 15:45 UTC, AlexMem approved these changes

2026-04-23 16:59 UTC, closed without merging