Task5  completed (Khvan)
elefus/epam-leti-10-2017 pull request #171
Opened 2017-11-15 11:46 UTC by Demetresko

Changes commited

2017-11-15 21:03 UTC, Hitsugaya7 commented on src/main/java/com/epam/jf/khvan/homework/Task5.java
> +                        consonantNumber = 0;
Твой код неправильно работает, так как переменные надо обнулять перед циклом for, потому что в этот блок кода нельзя зайти, если строка состоит из кириллицы 
Вот тебе входные данные которые я использовал : pQTгг is

2017-11-15 21:04 UTC, Hitsugaya7 commented on src/main/java/com/epam/jf/khvan/homework/Task5.java
> +        LinkedList<Character> vowels = new LinkedList<>(Arrays.asList('a','A','e','E','i','I','o','O','u','U','y','Y'));
Чтобы не работать и со строчными и с заглавными буквами, можно всю строчку привести к заглавным или к строчным буквам с помощью методов toLowerCase() или toUpperCase().

2017-11-15 21:44 UTC, Demetresko commented on src/main/java/com/epam/jf/khvan/homework/Task5.java
> +                        consonantNumber = 0;
Переделал

2017-11-22 11:37 UTC, RicoRodriges requested changes
Неправильно использовал continue. Подходит слово 123ab

2017-11-23 21:47 UTC, MrBender13 reviewed
Счётчики лучше объявить и проинициализировать во внешнем цикле, тогда во внутреннем можно избежать одной проверки и повторения кода.
Если мы наткнулись на не латинский символ, то не лучше ли покинуть вложенный цикл с помощью break(вместо continue)? Ведь такое слово уже точно не подойдёт.

2017-11-26 16:51 UTC, Demetresko commented
conflicts resolved

2017-12-15 10:17 UTC, egakupi requested changes
Разреши конфликт, а так всё хорошо

2026-08-19 13:37 UTC, closed without merging