Task 15 completed (Ilyinykh)
elefus/epam-leti-10-2017 pull request #179
Opened 2017-11-15 23:01 UTC by IlyasYOY

2017-12-05 20:21 UTC, iBavtovich requested changes
Для отрицательно сдвига не работает

2017-12-07 18:57 UTC, iBavtovich approved these changes

2017-12-20 22:12 UTC, Demetresko approved these changes

2018-01-09 18:50 UTC, Constray approved these changes

2018-01-13 16:03 UTC, Awethon approved these changes

2018-10-25 14:25 UTC, closed without merging