Task 16 completed (Ilyinykh)
elefus/epam-leti-10-2017 pull request #212
Opened 2017-11-19 11:24 UTC by IlyasYOY

2017-11-26 16:58 UTC, Demetresko reviewed
мне кажется нужно добавить методы sort  и toArray

2017-12-05 07:06 UTC, tehwalkingwind approved these changes

2017-12-10 11:46 UTC, iBavtovich approved these changes

2017-12-12 14:41 UTC, elefus requested changes
Изменить целевую ветку

2018-01-13 15:58 UTC, AlexMem approved these changes

2018-10-25 14:25 UTC, closed without merging