Task5 completed (Khvan)
elefus/epam-leti-10-2017 pull request #89
Opened 2017-11-02 22:46 UTC by Demetresko

2017-11-02 22:54 UTC, Criptonite commented on src/main/java/com/epam/jf/khvan/homework/Task5.java
> +            if(isLetterEnglish==true){
Можно написать просто isLetterEnglish. Нет смысла делать isLetterEnglish==true

2017-11-12 22:38 UTC, Demetresko commented
errors fixed

2017-11-15 11:17 UTC, elefus requested changes
Изменить целевую ветку с master на khvan

2017-11-15 11:17 UTC, elefus commented on src/main/java/com/epam/jf/khvan/homework/Task5.java
> +                    isLetterEnglish = false;
В этот момент можно просто переходить к следующей итерации цикла с помощью оператора continue (флаг в этом случае не понадобится).

2017-11-15 11:17 UTC, elefus commented on src/main/java/com/epam/jf/khvan/homework/Task5.java
> +                for (int j = 0; j < lettersWord.length; j++){
Зачем делать два прохода по всем символам, если достаточно будет одного (если совместить проверку на принадлежность символа английскому алфовиту и гласные/согласные)?

2017-11-22 09:21 UTC, egakupi requested changes
Измени целевую ветку и исправь конфликт

2017-12-15 10:12 UTC, egakupi commented
Измени целевую ветку

2026-08-19 13:37 UTC, closed without merging